--WARNING: treasure same but diff description 30G 100
-- Non-MAGIC weakness for mob 18+2 Magic Damage
--WARNING: treasure same but diff description 150G/Gold A 150G/Red A
--WARNING: treasure same but diff description 180G/Gold White A 180/Gold Red A
--WARNING: treasure same but diff description 150G/Gold A 300G/Gold A
-- WARNING: treasure skipped but not same description 150G/Gold A 300G/Gold A
-- WARNING: treasure skipped but not same description 100G/Red A 100G/Red rounds
--WARNING: treasure same but diff description 150G/Gold A 300G/Gold A
--WARNING: treasure same but diff description 30G/Green B 600G/Gold Green A
--WARNING: treasure same but diff description 300G/Red A 300G/Gold A
--WARNING: treasure same but diff description 250G/Gold Red A 250/Gold Red A
--WARNING: treasure same but diff description 250G/Gold Red A 250/Gold Red A
--WARNING: treasure same but diff description 300G/Red A 300G/Gold A
--WARNING: treasure same but diff description 1,000G/White S 800G/Gold Black White A
-- WARNING: treasure skipped but not same description 300G/Red A 300G/Gold A
--WARNING: treasure same but diff description 1 pts.) (50G 2 pts.) (100G
--WARNING: treasure same but diff description 1 pts.) (50G 2 pts.)(100G
--WARNING: treasure same but diff description 1 pts.) (50G 5 pts.)(250G
--WARNING: treasure same but diff description 200G 200G/-
--WARNING: treasure same but diff description 150G/Gold A 600G/Gold A
--WARNING: treasure same but diff description 30G 50G
--WARNING: treasure same but diff description 30G 50G
--WARNING: treasure same but diff description 30G 50G
--WARNING: treasure same but diff description 30G 100G
--WARNING: treasure same but diff description 30G 50G
--WARNING: treasure same but diff description 30G 100G
--WARNING: treasure same but diff description 150G/Gold A 600G/Gold A
--WARNING: treasure same but diff description 150G/Gold A 300G/Gold A
--WARNING: treasure same but diff description 600G/Gold A 300G/Gold A
--WARNING: treasure same but diff description 50G 200G
--WARNING: treasure same but diff description 50G 300G
-- WARNING: treasure skipped but not same description 50G 100G
--WARNING: treasure same but diff description 50G 200G
--WARNING: treasure same but diff description 50G 300G
--WARNING: treasure same but diff description 30G 30G/-
-- WARNING: treasure skipped but not same description 150G/Black White A 150G / Black-White A
--WARNING: treasure same but diff description 30G 50G
--WARNING: treasure same but diff description 1,000G/Gold Black S 1000G / Gold Black S
-- WARNING: treasure skipped but not same description 1,000G/Red S 1000G / Red S
--WARNING: treasure same but diff description 100G/Red Green A 100G / Green A
--WARNING: treasure same but diff description 300G/Red A 300G / Gold A
--WARNING: treasure same but diff description 300G/Gold A 500G / Gold A
--WARNING: treasure same but diff description 200G/Gold Green A 200G/Red Green A
--WARNING: treasure same but diff description 500G/Gold Green A 500G/Red Green A
--WARNING: treasure same but diff description 200G/Gold Green A 200G/Red Green A
--WARNING: treasure same but diff description 500G/Gold Green A 500G/Red Green A
-- WARNING: treasure skipped but not same description 1,300G/Gold S 1,200G/Gold S
-- ERROR unsupported perception for mob 470 Magitech
-- WARNING: treasure skipped but not same description 50G 100G/-
--WARNING: treasure same but diff description 150G/Gold A 300G/Gold A
--WARNING: treasure same but diff description 150G/Gold A 500G/Gold A
--WARNING: treasure same but diff description 1 pts.) (50G 5 pts.) (250G/-
--WARNING: treasure same but diff description 1 pts.) (50G 10 pts.) (1,000G/-
--WARNING: treasure same but diff description 50G 30G/-
--WARNING: treasure same but diff description 50G 50G/-
--WARNING: treasure same but diff description 30G 50G/-
--WARNING: treasure same but diff description 30G 100G/-
--WARNING: treasure same but diff description 50G 50G/-
--WARNING: treasure same but diff description 600G/Gold A 150G/Gold A
--WARNING: treasure same but diff description 30G 100G/- 
--WARNING: treasure same but diff description 30G 100G/-
--WARNING: treasure same but diff description 30G 100G/-
-- WARNING: treasure skipped but not same description See above See Above
--WARNING: treasure same but diff description 30G 50G/-
--WARNING: treasure same but diff description 30G 100G/-
--WARNING: treasure same but diff description 150G/Gold A 300G/Gold A
--WARNING: treasure same but diff description 50G 300G/-
--WARNING: treasure same but diff description 50G 400G/-
--WARNING: treasure same but diff description 4,000G/Gold S 400G / Gold S
--WARNING: treasure same but diff description 2,400G/Black White S 2,400G/Black White A
--WARNING: treasure same but diff description 1,000G/Black White S 1,000G/Gold Black White S
--WARNING: treasure same but diff description 100G/Red A 160G/Red A
--WARNING: treasure same but diff description 200G 200G/-
--WARNING: treasure same but diff description 100G/Red Green A 100G/Green A
--WARNING: treasure same but diff description 30G 30G/-
--WARNING: treasure same but diff description 1,000G/Black White S 4,000G/Black White S
--WARNING: treasure same but diff description 200G 200G/-
--WARNING: treasure same but diff description 200G 200G/-
--WARNING: treasure same but diff description 200G 200G/-
--WARNING: treasure same but diff description 200G 200G/-
--WARNING: treasure same but diff description 200G 200G/-
-- WARNING: treasure skipped but not same description 300G/Red A 300G/Gold A
-- ERROR unsupported perception for mob 627 Shared with Caster
-- WARNING: treasure skipped but not same description 200G 200G/-
-- WARNING: treasure skipped but not same description 200G 200G/-
-- ERROR unsupported perception for mob 631 Shared with Caster
--WARNING: treasure same but diff description 200G 200G/-
--WARNING: treasure same but diff description 200G 200G/-
-- WARNING: treasure skipped but not same description 200G 200G/-
-- WARNING: treasure skipped but not same description 200G 200G/-
--WARNING: treasure same but diff description 50G 50G/-
--WARNING: treasure same but diff description 50G 50G/-
--WARNING: treasure same but diff description 50G 100G/-
--WARNING: treasure same but diff description 30G 100G/-
--WARNING: treasure same but diff description 50G 100G/-
--WARNING: treasure same but diff description 30G 300G/-
--WARNING: treasure same but diff description 50G 300G/-
--WARNING: treasure same but diff description 600G/Gold A 150G/Gold A
Treasure_DB={}
Treasure_DB[TREASURES.CrudeWeapon] = Item:new( {name="Crude Weapon", worth=10, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.DirtyHood] = Item:new( {name="Dirty Hood", worth=20, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.SwordShardx5] = Item:new( {name="Sword Shard  x 5", worth=200, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.DraconianHorn] = Item:new( {name="Draconian Horn", worth=500, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.MajesticDraconianHorn] = Item:new( {name="Majestic Draconian Horn", worth=4200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.HighqualityWeapon] = Item:new( {name="High-quality Weapon", worth=150, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BagofSilverx1d] = Item:new( {name="Bag of Silver  x 1d", worth=30, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.Gemx1d] = Item:new( {name="Gem  x 1d", worth=150, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.StrangeNecklace] = Item:new( {name="Strange Necklace", worth=160, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.Weapon] = Item:new( {name="Weapon", worth=30, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.WornHood] = Item:new( {name="Worn Hood", worth=80, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.SahaginTrident] = Item:new( {name="Sahagin Trident", worth=30, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.OrnateTrident] = Item:new( {name="Ornate Trident", worth=120, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.AmberScales] = Item:new( {name="Amber Scales", worth=90, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.BattleGear] = Item:new( {name="Battle Gear", worth=30, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.FineOutfit] = Item:new( {name="Fine Outfit", worth=120, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.CrudeShield] = Item:new( {name="Crude Shield", worth=50, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.HookRopex2] = Item:new( {name="Hook Rope  x 2", worth=50, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.ExtravagantWeapon] = Item:new( {name="Extravagant Weapon", worth=500, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ViperofMedusa] = Item:new( {name="Viper of Medusa", worth=50, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.EyesofStone] = Item:new( {name="Eyes of Stone", worth=1200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.SevencolorScales] = Item:new( {name="Seven-color Scales", worth=220, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.LizardmanFlag] = Item:new( {name="Lizardman Flag", worth=100, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.WaterFeatheredKimono] = Item:new( {name="Water Feathered Kimono", worth=100, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BeautifulFeatheredKimono] = Item:new( {name="Beautiful Feathered Kimono", worth=300, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ShiningFeatheredKimono] = Item:new( {name="Shining Feathered Kimono", worth=1000, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.BeautifulFeathers] = Item:new( {name="Beautiful Feathers", worth=30, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.SevencoloredFeather] = Item:new( {name="Seven-colored Feather", worth=200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BarbarousOrders] = Item:new( {name="Barbarous' Orders", worth=500, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.NightRobe] = Item:new( {name="Night Robe", worth=280, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.RustySpear] = Item:new( {name="Rusty Spear", worth=50, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.BeautifulShell] = Item:new( {name="Beautiful Shell", worth=180, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.AbyssShard] = Item:new( {name="Abyss Shard", worth=200, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.BlackGem] = Item:new( {name="Black Gem", worth=300, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BlackGemx2] = Item:new( {name="Black Gem  x 2", worth=300, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BlackGemx1d] = Item:new( {name="Black Gem  x 1d", worth=300, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.OminousBranches] = Item:new( {name="Ominous Branches", worth=130, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.FieryResidue] = Item:new( {name="Fiery Residue", worth=900, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.Shieldwithasophisticateddesign] = Item:new( {name="Shield with a sophisticated design", worth=150, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.Luxuriousshield] = Item:new( {name="Luxurious shield", worth=500, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.HeraldicSpear] = Item:new( {name="Heraldic Spear", worth=150, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.WellBalancedSpear] = Item:new( {name="Well-Balanced Spear", worth=600, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.TrollBlood] = Item:new( {name="Troll Blood", worth=100, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.LargeWeapon] = Item:new( {name="Large Weapon", worth=300, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.Gemsx1d] = Item:new( {name="Gems  x 1d", worth=150, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SilverPearl] = Item:new( {name="Silver Pearl", worth=3000, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.WaterrepellentSkin] = Item:new( {name="Water-repellent Skin", worth=330, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SwordShard] = Item:new( {name="Sword Shard", worth=200, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.SwordShardx3] = Item:new( {name="Sword Shard  x 3", worth=200, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.JellylikeMaterial] = Item:new( {name="Jelly-like Material", worth=100, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.JellylikeHeart] = Item:new( {name="Jelly-like Heart", worth=300, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.MiniBlob] = Item:new( {name="Mini-Blob", worth=1500, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.DangerousPincers] = Item:new( {name="Dangerous Pincers", worth=570, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.DeadlyPincers] = Item:new( {name="Deadly Pincers", worth=1660, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.RobeofDarkness] = Item:new( {name="Robe of Darkness", worth=780, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.MinotaursAxe] = Item:new( {name="Minotaur's Axe", worth=475, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BigHorn] = Item:new( {name="Big Horn", worth=150, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BeautifulHorn] = Item:new( {name="Beautiful Horn", worth=600, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SilverMedal] = Item:new( {name="Silver Medal", worth=700, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.Gems] = Item:new( {name="Gems", worth=150, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.OminousBranchesx2] = Item:new( {name="Ominous Branches  x 2", worth=130, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.VindictiveResidue] = Item:new( {name="Vindictive Residue", worth=2400, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.Spellbook] = Item:new( {name="Spellbook", worth=500, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.EsotericSpellbook] = Item:new( {name="Esoteric Spellbook", worth=1500, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.StrangeHolySymbol] = Item:new( {name="Strange Holy Symbol", worth=3300, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.WellKeptWeapon] = Item:new( {name="Well-Kept Weapon", worth=1000, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.ThunderHorn] = Item:new( {name="Thunder Horn", worth=2100, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.GlossySkin] = Item:new( {name="Glossy Skin", worth=1720, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.BeastmanFur] = Item:new( {name="Beastman Fur", worth=200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ShiningFur] = Item:new( {name="Shining Fur", worth=1200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.BasiliskBlood] = Item:new( {name="Basilisk Blood", worth=200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.PetrifyingEyes] = Item:new( {name="Petrifying Eyes", worth=1200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.GoldBracelet] = Item:new( {name="Gold Bracelet", worth=2500, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.VeteranPincers] = Item:new( {name="Veteran Pincers", worth=4400, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.ShiningSevencoloredScales] = Item:new( {name="Shining Seven-colored Scales", worth=570, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.MajesticHorn] = Item:new( {name="Majestic Horn", worth=3500, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.DazzlingFeathers] = Item:new( {name="Dazzling Feathers", worth=2000, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.OminousBranchesx1d] = Item:new( {name="Ominous Branches  x 1d", worth=130, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BarbarousDecree] = Item:new( {name="Barbarous Decree", worth=500, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ExtravagantWeaponx2] = Item:new( {name="Extravagant Weapon  x 2", worth=500, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.WellKeptWeaponx2] = Item:new( {name="Well-Kept Weapon  x 2", worth=1000, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.RareWeaponx2] = Item:new( {name="Rare Weapon  x 2", worth=4000, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.AbyssShardx2] = Item:new( {name="Abyss Shard  x 2", worth=200, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.JetBlackGemx2] = Item:new( {name="Jet-Black Gem  x 2", worth=2200, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.TheLustrousBloodofMurcielago] = Item:new( {name="The Lustrous Blood of Murcielago", worth=2000, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.BarbarousDirectives] = Item:new( {name="Barbarous Directives", worth=500, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BloodFamilyDirectives] = Item:new( {name="Blood Family Directives", worth=5000, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.CorruptedAsh] = Item:new( {name="Corrupted Ash", worth=300, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.VampireCloak] = Item:new( {name="Vampire Cloak", worth=1000, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.JetBlackCloak] = Item:new( {name="Jet-Black Cloak", worth=5000, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.RareGrimoire] = Item:new( {name="Rare Grimoire", worth=3000, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.SuccubusPerfume] = Item:new( {name="Succubus Perfume", worth=400, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BeautifulTail] = Item:new( {name="Beautiful Tail", worth=3000, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.CaptivatingTail] = Item:new( {name="Captivating Tail", worth=7000, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.LuxuryOrnamentsx2d] = Item:new( {name="Luxury Ornaments  x 2d", worth=500, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.RoyalTreasuredSword] = Item:new( {name="Royal Treasured Sword", worth=8000, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.BasiliskPureblood] = Item:new( {name="Basilisk Pureblood", worth=1000, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.OnyxEye] = Item:new( {name="Onyx Eye", worth=4000, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.EyeofStagnation] = Item:new( {name="Eye of Stagnation", worth=10000, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.SoldiersOutfit] = Item:new( {name="Soldier's Outfit", worth=500, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GoldenBattleOutfit] = Item:new( {name="Golden Battle Outfit", worth=3200, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.TheLustrousBloodofMurcielagox1d] = Item:new( {name="The Lustrous Blood of Murcielago  x 1d", worth=2000, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.AbyssShardx5] = Item:new( {name="Abyss Shard  x 5", worth=200, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.TrueDarkGemx2] = Item:new( {name="True Dark Gem  x 2", worth=4900, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.AbyssalTreasurex2] = Item:new( {name="Abyssal Treasure  x 2", worth=15500, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.BeautifulTetrahedron] = Item:new( {name="Beautiful Tetrahedron", worth=6000, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.GlassesoftheImmortal] = Item:new( {name="Glasses of the Immortal", worth=3500, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.GoldenRecordingGlassesoftheImmortal] = Item:new( {name="Golden Recording Glasses of the Immortal", worth=16500, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.WolfHide20GRedB] = Item:new( {name="Wolf Hide (20G/Red B", worth=0, alchemy_color={  }, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.HighqualityWolfHide] = Item:new( {name="High-quality Wolf Hide", worth=50, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.FlawlessWolfHide] = Item:new( {name="Flawless Wolf Hide", worth=100, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BlackenedCompoundEyes] = Item:new( {name="Blackened Compound Eyes", worth=30, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.ShinyCompoundEyes] = Item:new( {name="Shiny Compound Eyes", worth=150, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.HighqualityJade] = Item:new( {name="High-quality Jade", worth=140, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.PearlFragments] = Item:new( {name="Pearl Fragments", worth=50, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.OceanPearl] = Item:new( {name="Ocean Pearl", worth=200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.VioletJewel] = Item:new( {name="Violet Jewel", worth=120, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GreyLynxFur] = Item:new( {name="Grey Lynx Fur", worth=80, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.MysteriousSeeds] = Item:new( {name="Mysterious Seeds", worth=100, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.WolfHide] = Item:new( {name="Wolf Hide", worth=20, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.ThinNails] = Item:new( {name="Thin Nails", worth=120, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SharpPincers] = Item:new( {name="Sharp Pincers", worth=50, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.CrabInnards] = Item:new( {name="Crab Innards", worth=600, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.CrocodileSkin] = Item:new( {name="Crocodile Skin", worth=200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SuperiorCrocodileSkin] = Item:new( {name="Superior Crocodile Skin", worth=600, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SandwormGem] = Item:new( {name="Sandworm Gem", worth=150, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GreenSandwormGemx1d] = Item:new( {name="Green Sandworm Gem  x 1d", worth=200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.StickyWater] = Item:new( {name="Sticky Water", worth=200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.VeryStickyWater] = Item:new( {name="Very Sticky Water", worth=680, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.LargeFang] = Item:new( {name="Large Fang", worth=100, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.TigerPelt] = Item:new( {name="Tiger Pelt", worth=200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.FineTigerPelt] = Item:new( {name="Fine Tiger Pelt", worth=600, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.HighQualityShell] = Item:new( {name="High-Quality Shell", worth=1200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.Fur] = Item:new( {name="Fur", worth=150, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BearPaws] = Item:new( {name="Bear Paws", worth=300, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.AromaticBearPaws] = Item:new( {name="Aromatic Bear Paws", worth=1200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.RedBodyFluid] = Item:new( {name="Red Body Fluid", worth=550, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.FineSnakeSkin] = Item:new( {name="Fine Snake Skin", worth=120, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.PremiumSnakeSkin] = Item:new( {name="Premium Snake Skin", worth=320, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SharpFangsx2] = Item:new( {name="Sharp Fangs  x 2", worth=200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ShiningFangx2] = Item:new( {name="Shining Fang  x 2", worth=600, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.FeathersoftheBirdofPrey] = Item:new( {name="Feathers of the Bird of Prey", worth=400, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.FineFur] = Item:new( {name="Fine Fur", worth=450, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GlossyFur] = Item:new( {name="Glossy Fur", worth=150, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SnowWhiteFur] = Item:new( {name="Snow White Fur", worth=2600, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.DeadlyPoisonousNeedle] = Item:new( {name="Deadly Poisonous Needle", worth=2400, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.ClearIceDeerAntlers] = Item:new( {name="Clear Ice Deer Antlers", worth=7400, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.CrystallizedIceDeerAntlers] = Item:new( {name="Crystallized Ice Deer Antlers", worth=14800, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.SteamDistillation] = Item:new( {name="Steam Distillation", worth=30, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.SteamVineSeeds] = Item:new( {name="Steam Vine Seeds", worth=120, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.CrimsonPetals] = Item:new( {name="Crimson Petals", worth=120, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ElasticVines] = Item:new( {name="Elastic Vines", worth=120, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.MagicalVine] = Item:new( {name="Magical Vine", worth=30, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.StrongVine] = Item:new( {name="Strong Vine", worth=300, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.DiffusedFruitJuice] = Item:new( {name="Diffused Fruit Juice", worth=150, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ConcentratedFruitJuice] = Item:new( {name="Concentrated Fruit Juice", worth=650, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GreenDyex1d] = Item:new( {name="Green Dye  x 1d", worth=80, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.FertileSoil] = Item:new( {name="Fertile Soil", worth=300, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.AbundantSoil] = Item:new( {name="Abundant Soil", worth=2000, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.WiltedMushrooms] = Item:new( {name="Wilted Mushrooms", worth=30, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.ForestMarvel] = Item:new( {name="Forest Marvel", worth=2000, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.ForestMarvelx3] = Item:new( {name="Forest Marvel  x 3", worth=2000, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.MagicBark] = Item:new( {name="Magic Bark", worth=4000, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.AbyssTreeLeavesx2d] = Item:new( {name="Abyss Tree Leaves  x 2d", worth=300, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GrayBarkx1d] = Item:new( {name="Gray Bark  x 1d", worth=400, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SturdyBones] = Item:new( {name="Sturdy Bones", worth=30, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.MagicalBones] = Item:new( {name="Magical Bones", worth=250, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.CrystalTearsofResentment] = Item:new( {name="Crystal Tears of Resentment", worth=500, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ZombieEye] = Item:new( {name="Zombie Eye", worth=30, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.ZombieEyex2] = Item:new( {name="Zombie Eye  x 2", worth=30, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.GhoulToxinExtract] = Item:new( {name="Ghoul Toxin Extract", worth=20, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.GhoulCoin] = Item:new( {name="Ghoul Coin", worth=300, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SoulscarredBirdSkull] = Item:new( {name="Soulscarred Bird Skull", worth=250, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.TaintedSkull] = Item:new( {name="Tainted Skull", worth=300, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.RustySword] = Item:new( {name="Rusty Sword", worth=50, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.OrnateSwordHilt] = Item:new( {name="Ornate Sword Hilt", worth=600, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BrokenMemento] = Item:new( {name="Broken Memento", worth=500, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.Memento] = Item:new( {name="Memento", worth=1000, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.RareGhoulCoinx1d] = Item:new( {name="Rare Ghoul Coin  x 1d", worth=350, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.OldCloak] = Item:new( {name="Old Cloak", worth=200, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.AncientCloak] = Item:new( {name="Ancient Cloak", worth=800, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.IceCrystal] = Item:new( {name="Ice Crystal", worth=1600, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.MissingBones] = Item:new( {name="Missing Bones", worth=80, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.AncientRobe] = Item:new( {name="Ancient Robe", worth=3300, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.CrystalTearsofSorrow] = Item:new( {name="Crystal Tears of Sorrow", worth=1000, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.YellowedGoldenRing] = Item:new( {name="Yellowed Golden Ring", worth=1000, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.YellowedGoldenBracelet] = Item:new( {name="Yellowed Golden Bracelet", worth=2000, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.StaffoftheWizardKing] = Item:new( {name="Staff of the Wizard-King", worth=3000, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.GoldenMask] = Item:new( {name="Golden Mask", worth=15000, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.SkullofaDefiledMythicalBeast] = Item:new( {name="Skull of a Defiled Mythical Beast", worth=1500, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.FrozenMana] = Item:new( {name="Frozen Mana", worth=5000, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.WellkeptWeapon] = Item:new( {name="Well-kept Weapon", worth=1000, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.MagicalStone] = Item:new( {name="Magical Stone", worth=250, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.MakoStone] = Item:new( {name="Mako Stone", worth=150, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.EnchantedStone] = Item:new( {name="Enchanted Stone", worth=250, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.TaintedMucus] = Item:new( {name="Tainted Mucus", worth=80, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.SoulscarredMucus] = Item:new( {name="Soulscarred Mucus", worth=440, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.MagicalWood] = Item:new( {name="Magical Wood", worth=200, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.PremiumMagicalWood] = Item:new( {name="Premium Magical Wood", worth=500, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.DenseMagicJewel] = Item:new( {name="Dense Magic Jewel", worth=700, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.EnchantedOakBranch] = Item:new( {name="Enchanted Oak Branch", worth=200, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.AncientWritings] = Item:new( {name="Ancient Writings", worth=2000, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.LightningCrystal] = Item:new( {name="Lightning Crystal", worth=1600, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.LuxuryMagicalWood] = Item:new( {name="Luxury Magical Wood", worth=3600, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.ExquisiteHorn] = Item:new( {name="Exquisite Horn", worth=900, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.LuxuryHorn] = Item:new( {name="Luxury Horn", worth=5800, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.GreenLightPowder] = Item:new( {name="Green Light Powder", worth=520, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GreenLightPowderx1d] = Item:new( {name="Green Light Powder  x 1d", worth=520, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GoldenSerumx1d] = Item:new( {name="Golden Serum  x 1d", worth=300, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GoldenScales] = Item:new( {name="Golden Scales", worth=600, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GiantEyeball] = Item:new( {name="Giant Eyeball", worth=500, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.CrystallizedMagicalEye] = Item:new( {name="Crystallized Magical Eye", worth=1000, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.CrystallizedMagicalEyesx1d] = Item:new( {name="Crystallized Magical Eyes  x 1d", worth=1000, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.CrystallizedMagicalEyesx2d] = Item:new( {name="Crystallized Magical Eyes  x 2d", worth=1000, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.MagicalGoldNuggets] = Item:new( {name="Magical Gold Nuggets", worth=2000, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.Mithril] = Item:new( {name="Mithril", worth=2600, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.PureMithril] = Item:new( {name="Pure Mithril", worth=8800, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.Iron] = Item:new( {name="Iron", worth=20, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.CrudeMagitechComponents] = Item:new( {name="Crude Magitech Components", worth=100, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.DaemonResistantMaterial] = Item:new( {name="Daemon-Resistant Material", worth=40, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.MagitechComponents] = Item:new( {name="Magitech Components", worth=300, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.RareMagitechComponents] = Item:new( {name="Rare Magitech Components", worth=900, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.MysteriousMagitechComponents] = Item:new( {name="Mysterious Magitech Components", worth=2400, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.PlayCards] = Item:new( {name="Play Cards", worth=50, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.TroveofMagicalComponents] = Item:new( {name="Trove of Magical Components", worth=7600, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.BrokenMagitechComponentsx5] = Item:new( {name="Broken Magitech Components  x 5", worth=50, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.ArcanaLanguageBookx1d] = Item:new( {name="Arcana-Language Book  x 1d", worth=170, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.KamawetFangs] = Item:new( {name="Kamawet Fangs", worth=500, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.MythicalBeastHide] = Item:new( {name="Mythical Beast Hide", worth=140, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.FlameCrystal] = Item:new( {name="Flame Crystal", worth=1600, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.WhiteFeathers] = Item:new( {name="White Feathers", worth=50, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.PureWhiteMane] = Item:new( {name="Pure White Mane", worth=800, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.FineMythicalBeastHide] = Item:new( {name="Fine Mythical Beast Hide", worth=300, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BeautifulMythicalBeastHide] = Item:new( {name="Beautiful Mythical Beast Hide", worth=800, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GreenHair] = Item:new( {name="Green Hair", worth=250, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.CleanGreenHair] = Item:new( {name="Clean Green Hair", worth=750, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.UnicornHorn] = Item:new( {name="Unicorn Horn", worth=300, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GrayishWhiteFur] = Item:new( {name="Grayish-White Fur", worth=600, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SilveryWhiteFur] = Item:new( {name="Silvery-White Fur", worth=2100, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.SilverwhiteMythicalBeastHide] = Item:new( {name="Silver-white Mythical Beast Hide", worth=3600, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.LightSoundingBellx1d] = Item:new( {name="Light Sounding Bell  x 1d", worth=200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.ClearSoundingBell] = Item:new( {name="Clear Sounding Bell", worth=2680, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.PetrifyingHoovesx2] = Item:new( {name="Petrifying Hooves  x 2", worth=1200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.SlimySkin] = Item:new( {name="Slimy Skin", worth=680, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.CockatriceBeak] = Item:new( {name="Cockatrice Beak", worth=1000, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.CrimsonBeak] = Item:new( {name="Crimson Beak", worth=3200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.DaemonsBlood] = Item:new( {name="Daemon's Blood", worth=100, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.PoisonTail] = Item:new( {name="Poison Tail", worth=150, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.DaemonsFangs] = Item:new( {name="Daemon's Fangs", worth=300, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.DaemonsSharpLegs] = Item:new( {name="Daemon's Sharp Legs", worth=170, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.DaemonsRazorLegs] = Item:new( {name="Daemon's Razor Legs", worth=530, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.DaemonsEarrings] = Item:new( {name="Daemon's Earrings", worth=260, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.DaemonsRing] = Item:new( {name="Daemon's Ring", worth=600, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BlackHide] = Item:new( {name="Black Hide", worth=4600, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.SturdyShell] = Item:new( {name="Sturdy Shell", worth=200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.TwistedBlackHorn] = Item:new( {name="Twisted Black Horn", worth=380, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.TwistedJetBlackHorn] = Item:new( {name="Twisted Jet-Black Horn", worth=1480, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.CrystallizedDaemonsBlood] = Item:new( {name="Crystallized Daemon's Blood", worth=800, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.TransparentLeather] = Item:new( {name="Transparent Leather", worth=1400, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.DaemonsCrystal] = Item:new( {name="Daemon's Crystal", worth=800, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SolidifiedDroplets] = Item:new( {name="Solidified Droplets", worth=2500, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.CrushedGemstonePowder] = Item:new( {name="Crushed Gemstone Powder", worth=1600, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.Gemx2d] = Item:new( {name="Gem  x 2d", worth=600, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.OldGrimoire] = Item:new( {name="Old Grimoire", worth=4000, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.AncientGrimoire] = Item:new( {name="Ancient Grimoire", worth=9000, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.IncomprehensibleMask] = Item:new( {name="Incomprehensible Mask", worth=2000, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.DaemonsFiber] = Item:new( {name="Daemon's Fiber", worth=1100, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.LustrousDaemonsFiber] = Item:new( {name="Lustrous Daemon's Fiber", worth=4400, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.DaemonsArrowheadx2d] = Item:new( {name="Daemon's Arrowhead  x 2d", worth=100, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BagofSilver] = Item:new( {name="Bag of Silver", worth=50, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.BagofSilverx2d] = Item:new( {name="Bag of Silver  x 2d", worth=50, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.FineInstrument] = Item:new( {name="Fine Instrument", worth=100, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.LuxuryInstrument] = Item:new( {name="Luxury Instrument", worth=800, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.RareInstrument] = Item:new( {name="Rare Instrument", worth=3600, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.AlchemyKit] = Item:new( {name="Alchemy Kit", worth=100, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.ARankMaterialCardx2d] = Item:new( {name="A Rank Material Card  x 2d", worth=100, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.Gem] = Item:new( {name="Gem", worth=600, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.FairyTamersGemx4] = Item:new( {name="Fairy Tamer's Gem  x 4", worth=125, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.LargeGem] = Item:new( {name="Large Gem", worth=4000, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.WellKeptLargeShield] = Item:new( {name="Well-Kept Large Shield", worth=4000, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.EnchantedStrawBundle] = Item:new( {name="Enchanted Straw Bundle", worth=150, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.EnchantedClay] = Item:new( {name="Enchanted Clay", worth=250, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.EnchantedAnimalBones] = Item:new( {name="Enchanted Animal Bones", worth=250, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.EnchantedLeather] = Item:new( {name="Enchanted Leather", worth=150, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.Treasurex1d] = Item:new( {name="Treasure  x 1d", worth=200, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.KeenWeapon] = Item:new( {name="Keen Weapon", worth=100, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BeautifulNecklace] = Item:new( {name="Beautiful Necklace", worth=300, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.DanceCostume] = Item:new( {name="Dance Costume", worth=100, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.LongFlexibleWhip] = Item:new( {name="Long, Flexible Whip", worth=140, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.VialofPhytotoxin] = Item:new( {name="Vial of Phytotoxin", worth=150, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BottleofPhytotoxin] = Item:new( {name="Bottle of Phytotoxin", worth=300, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BarbarousFlag] = Item:new( {name="Barbarous Flag", worth=2000, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.ExplosiveReactantCrystalDebris] = Item:new( {name="Explosive Reactant Crystal Debris", worth=600, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.FragmentofExplosiveReactantCrystal] = Item:new( {name="Fragment of Explosive Reactant Crystal", worth=1600, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.ShatteredIgnisOreCore] = Item:new( {name="Shattered Ignis Ore Core", worth=300, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.CrackedIgnisOreCore] = Item:new( {name="Cracked Ignis Ore Core", worth=1000, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.FrozenFangx2] = Item:new( {name="Frozen Fang  x 2", worth=330, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.FrozenFangx1d] = Item:new( {name="Frozen Fang  x 1d", worth=330, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GoblinCrown] = Item:new( {name="Goblin Crown", worth=700, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.EngravedWeapon] = Item:new( {name="Engraved Weapon", worth=600, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.WhiteScalesx1d] = Item:new( {name="White Scales  x 1d", worth=90, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.RainbowHuedScalesx1d] = Item:new( {name="Rainbow Hued Scales  x 1d", worth=220, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.FlexibleWhip] = Item:new( {name="Flexible Whip", worth=140, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BeastTamersWhip] = Item:new( {name="Beast Tamer's Whip", worth=660, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GrayCloak] = Item:new( {name="Gray Cloak", worth=300, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GlitteringNecklace] = Item:new( {name="Glittering Necklace", worth=2000, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.WellKeptSpear] = Item:new( {name="Well-Kept Spear", worth=1000, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.RareWeapon] = Item:new( {name="Rare Weapon", worth=4000, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.WhipofSubjugation] = Item:new( {name="Whip of Subjugation", worth=1680, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.DullIgnisOreCore] = Item:new( {name="Dull Ignis Ore Core", worth=4000, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.NobleBarbarousBanner] = Item:new( {name="Noble Barbarous' Banner", worth=5500, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.LuxuryOrnamentsx1d] = Item:new( {name="Luxury Ornaments  x 1d", worth=500, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.HeraldicRingx1d] = Item:new( {name="Heraldic Ring  x 1d", worth=3000, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.GlassEye] = Item:new( {name="Glass Eye", worth=2400, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.GlazedEye] = Item:new( {name="Glazed Eye", worth=6000, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.DirtyTeeth] = Item:new( {name="Dirty Teeth", worth=50, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.ToadOil] = Item:new( {name="Toad Oil/", worth=20, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.ClarifiedToadOil] = Item:new( {name="Clarified Toad Oil", worth=100, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.HardBeak] = Item:new( {name="Hard Beak", worth=60, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.FlightFeathers] = Item:new( {name="Flight Feathers", worth=100, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.IcyClaw] = Item:new( {name="Icy Claw", worth=100, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.IcyShell] = Item:new( {name="Icy Shell", worth=200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SnowWhiteShell] = Item:new( {name="Snow White Shell", worth=600, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GougingBeak] = Item:new( {name="Gouging Beak", worth=220, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GoodQualityShell] = Item:new( {name="Good Quality Shell", worth=150, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SuperiorShell] = Item:new( {name="Superior Shell", worth=750, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.LionsMane] = Item:new( {name="Lion's Mane", worth=150, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GoldenMane] = Item:new( {name="Golden Mane", worth=900, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.LargeFangx2] = Item:new( {name="Large Fang  x2", worth=100, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BrokenPawBlade] = Item:new( {name="Broken Paw Blade", worth=400, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.WiredHair] = Item:new( {name="Wired Hair", worth=870, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.SharpWiredHair] = Item:new( {name="Sharp Wired Hair", worth=2880, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.WhiteGoldMane] = Item:new( {name="White Gold Mane", worth=1900, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.PollenBall] = Item:new( {name="Pollen Ball", worth=60, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.VitalityRoot] = Item:new( {name="Vitality Root", worth=100, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.MandrakeSeed] = Item:new( {name="Mandrake Seed", worth=1500, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.MagicalVinex1d] = Item:new( {name="Magical Vine  x 1d", worth=80, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.RemainsoftheDead] = Item:new( {name="Remains of the Dead", worth=500, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SlimyTentacles] = Item:new( {name="Slimy Tentacles", worth=300, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.PetrifyingPoisonGland] = Item:new( {name="Petrifying Poison Gland", worth=100, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.DeadlyPetrifyingPoisonGland] = Item:new( {name="Deadly Petrifying Poison Gland", worth=500, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.PetrifyingPoisonCrystal] = Item:new( {name="Petrifying Poison Crystal", worth=200, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.PoisonousNeedle] = Item:new( {name="Poisonous Needle", worth=50, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.PoisonFrogFluid] = Item:new( {name="Poison Frog Fluid", worth=90, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.SturdyHindLegs] = Item:new( {name="Sturdy Hind Legs", worth=160, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ThickHindLegs] = Item:new( {name="Thick Hind Legs", worth=460, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.WightClaw] = Item:new( {name="Wight Claw", worth=50, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.CursedClaw] = Item:new( {name="Cursed Claw", worth=400, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BeastSkeleton] = Item:new( {name="Beast Skeleton", worth=60, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.SwordShardx1d] = Item:new( {name="Sword Shard x 1d", worth=0, alchemy_color={  }, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.SacredSwordHilt] = Item:new( {name="Sacred Sword Hilt", worth=1000, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SinisterCursedClaw] = Item:new( {name="Sinister Cursed Claw", worth=1070, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.GhoulToxinExtractx2] = Item:new( {name="Ghoul Toxin Extract  x 2", worth=20, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.PoisonousClaws] = Item:new( {name="Poisonous Claws", worth=1600, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.MagicIronIngot] = Item:new( {name="Magic Iron Ingot", worth=680, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.BindingChain] = Item:new( {name="Binding Chain", worth=500, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.JetblackBindingChain] = Item:new( {name="Jet-black Binding Chain", worth=3000, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.OldGoldCoin] = Item:new( {name="Old Gold Coin", worth=100, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.TransparentCloth] = Item:new( {name="Transparent Cloth", worth=250, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GlowingCloth] = Item:new( {name="Glowing Cloth", worth=1500, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.MagicStones] = Item:new( {name="Magic Stones", worth=1900, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.GlitteringMagicStone] = Item:new( {name="Glittering Magic Stone", worth=1300, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.GoldenBookmark] = Item:new( {name="Golden Bookmark", worth=1000, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.SophisticatedResearchData] = Item:new( {name="Sophisticated Research Data", worth=4000, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.OldRecordingDevice] = Item:new( {name="Old Recording Device", worth=100, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.LemmingsTooth] = Item:new( {name="Lemming's Tooth", worth=30, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.DragonFang] = Item:new( {name="Dragon Fang", worth=1200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.SharpHoof] = Item:new( {name="Sharp Hoof", worth=950, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.Gemsx2d] = Item:new( {name="Gems  x 2d", worth=150, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SerpentDaemonsFeathers] = Item:new( {name="Serpent Daemon's Feathers", worth=90, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.PieceofFleshx1d] = Item:new( {name="Piece of Flesh  x 1d", worth=30, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.LovelyNails] = Item:new( {name="Lovely Nails", worth=250, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BlackSpike] = Item:new( {name="Black Spike", worth=440, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.JetBlackSpike] = Item:new( {name="Jet Black Spike", worth=990, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.DaemonWings] = Item:new( {name="Daemon Wings", worth=350, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.RainbowDaemonWings] = Item:new( {name="Rainbow Daemon Wings", worth=1500, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.OrdinaryGrimoire] = Item:new( {name="Ordinary Grimoire", worth=500, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.RareGrimoirex2] = Item:new( {name="Rare Grimoire  x 2", worth=3000, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.DaemonWingsx2d] = Item:new( {name="Daemon Wings  x 2d", worth=350, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.RainbowDaemonWingsx1d] = Item:new( {name="Rainbow Daemon Wings  x 1d", worth=1500, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.RemainingMakoStones] = Item:new( {name="Remaining Mako Stones", worth=0, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.Magisphere] = Item:new( {name="Magisphere", worth=500, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.CustomizedWeapon] = Item:new( {name="Customized Weapon", worth=5000, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.MysteriousShells] = Item:new( {name="Mysterious Shells", worth=130, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BeetleShell] = Item:new( {name="Beetle Shell", worth=30, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.SharpWeaponx2] = Item:new( {name="Sharp Weapon  x 2", worth=100, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.HighqualityWeaponx2] = Item:new( {name="High-quality Weapon  x 2", worth=150, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GlitteringFeathers] = Item:new( {name="Glittering Feathers", worth=340, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GlitteringFeathersx2] = Item:new( {name="Glittering Feathers  x 2", worth=340, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.JaggedTooth] = Item:new( {name="Jagged Tooth", worth=30, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.CleanGills] = Item:new( {name="Clean Gills", worth=200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ThinWings] = Item:new( {name="Thin Wings", worth=120, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.WhiteMycelium] = Item:new( {name="White Mycelium", worth=300, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.RedSandwormGem] = Item:new( {name="Red Sandworm Gem", worth=900, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.IceNeedle] = Item:new( {name="Ice Needle", worth=150, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GlacialNeedle] = Item:new( {name="Glacial Needle", worth=600, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.PureIceNeedle] = Item:new( {name="Pure Ice Needle", worth=2400, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.StrangeEye] = Item:new( {name="Strange Eye", worth=80, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.BlueStrangeEye] = Item:new( {name="Blue Strange Eye", worth=160, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.StrangeWhiteEye] = Item:new( {name="Strange White Eye", worth=1200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.MightyVine] = Item:new( {name="Mighty Vine", worth=300, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.EntLeavesx1d] = Item:new( {name="Ent Leaves  x 1d", worth=100, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.EntLeavesx2d] = Item:new( {name="Ent Leaves  x 2d", worth=100, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.AntisepticFur] = Item:new( {name="Antiseptic Fur", worth=600, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BirdSkullWithoutPower] = Item:new( {name="Bird Skull Without Power", worth=500, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.CrystalTearsofResentmentx2] = Item:new( {name="Crystal Tears of Resentment  x 2", worth=500, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.RehydratedMonsterRemains] = Item:new( {name="Rehydrated Monster Remains", worth=900, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.TaintedBones] = Item:new( {name="Tainted Bones", worth=50, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.RegenerativeNucleus] = Item:new( {name="Regenerative Nucleus", worth=250, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.MagicIronRing] = Item:new( {name="Magic Iron Ring", worth=2500, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.SignalCircuit] = Item:new( {name="Signal Circuit", worth=100, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.IntermediateSignalCircuit] = Item:new( {name="Intermediate Signal Circuit", worth=400, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.AdvancedSignalCircuit] = Item:new( {name="Advanced Signal Circuit", worth=800, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.Magispherex1d] = Item:new( {name="Magisphere  x 1d", worth=100, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.DirtyWeapon] = Item:new( {name="Dirty Weapon", worth=300, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SplendidFang] = Item:new( {name="Splendid Fang", worth=400, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SplendidFangx2] = Item:new( {name="Splendid Fang  x 2", worth=400, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.HighQualityWeapon] = Item:new( {name="High-Quality Weapon", worth=1500, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.DecoratedFangx2] = Item:new( {name="Decorated Fang  x 2", worth=1000, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.StimulatingSauce] = Item:new( {name="Stimulating Sauce", worth=160, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.RichLiver] = Item:new( {name="Rich Liver", worth=400, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SpottedFur] = Item:new( {name="Spotted Fur", worth=700, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.Fang] = Item:new( {name="Fang", worth=100, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.CrimsonFeathers] = Item:new( {name="Crimson Feathers", worth=450, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BuffaloWings] = Item:new( {name="Buffalo Wings", worth=300, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ThickBuffaloWings] = Item:new( {name="Thick Buffalo Wings", worth=1300, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.StripeMushroom] = Item:new( {name="Stripe Mushroom", worth=60, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.SporeBag] = Item:new( {name="Spore Bag", worth=30, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.ManainfusedAlgaex1d] = Item:new( {name="Mana-infused Algae  x 1d", worth=100, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.RotationMechanism] = Item:new( {name="Rotation Mechanism", worth=150, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SmallBlastFurnace] = Item:new( {name="Small Blast Furnace", worth=1200, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.RareMagitechParts] = Item:new( {name="Rare Magitech Parts", worth=900, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.FragileImplement] = Item:new( {name="Fragile Implement", worth=40, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.CheapWeapon] = Item:new( {name="Cheap Weapon", worth=10, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.WellMaintainedTrident] = Item:new( {name="Well-Maintained Trident", worth=1000, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.MyceliumBundle] = Item:new( {name="Mycelium Bundle", worth=100, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BlackMushroomBed] = Item:new( {name="Black Mushroom Bed", worth=600, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.HerosMark] = Item:new( {name="Hero's Mark", worth=10000, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.GrayMessyHairx1d] = Item:new( {name="Gray Messy Hair  x 1d", worth=120, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.SilverMessyHairx1d] = Item:new( {name="Silver Messy Hair  x 1d", worth=440, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ShellOil] = Item:new( {name="Shell Oil", worth=250, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.HighViscosityOil] = Item:new( {name="High Viscosity Oil", worth=720, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.GlitteringOil] = Item:new( {name="Glittering Oil", worth=2400, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.Mucus] = Item:new( {name="Mucus", worth=20, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.CheapMeat] = Item:new( {name="Cheap Meat", worth=100, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.HardSickle] = Item:new( {name="Hard Sickle", worth=50, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.HardSicklex2] = Item:new( {name="Hard Sickle  x 2", worth=50, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.BeetleShellx2d] = Item:new( {name="Beetle Shell  x 2d", worth=30, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.GlossyFurx2] = Item:new( {name="Glossy Fur  x 2", worth=150, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.FineMeat] = Item:new( {name="Fine Meat", worth=200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.AbyssShardx1d] = Item:new( {name="Abyss Shard  x 1d", worth=200, alchemy_color={}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.PurpleHoney] = Item:new( {name="Purple Honey", worth=40, alchemy_color={  ALCHEMY_COLORS.Green}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.CrystalTearsofRegret] = Item:new( {name="Crystal Tears of Regret", worth=250, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.CrystallizedTearsofRegret] = Item:new( {name="Crystallized Tears of Regret", worth=250, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.CrystalofMalice] = Item:new( {name="Crystal of Malice", worth=8000, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.WinterAttires] = Item:new( {name="Winter Attires", worth=720, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ThickWinterAttire] = Item:new( {name="Thick Winter Attire", worth=2160, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.FineWinterAttire] = Item:new( {name="Fine Winter Attire", worth=6480, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.ArtifactsoftheDead] = Item:new( {name="Artifacts of the Dead", worth=500, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ValuableHeirloom] = Item:new( {name="Valuable Heirloom", worth=1000, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.GorgeousHeirloom] = Item:new( {name="Gorgeous Heirloom", worth=6000, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.StrongAbyssalAcid] = Item:new( {name="Strong Abyssal Acid", worth=900, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.DangerousGas] = Item:new( {name="Dangerous Gas", worth=2400, alchemy_color={  ALCHEMY_COLORS.Gold}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.LoudHeart] = Item:new( {name="Loud Heart", worth=2770, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.BeatingHeart] = Item:new( {name="Beating Heart", worth=7700, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.FragmentofDisaster] = Item:new( {name="Fragment of Disaster", worth=900, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.FragmentofUnknownDisaster] = Item:new( {name="Fragment of Unknown Disaster", worth=3600, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.LargeFeathers] = Item:new( {name="Large Feathers", worth=200, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.BrokenHorn] = Item:new( {name="Broken Horn", worth=30, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.DangerousHorns] = Item:new( {name="Dangerous Horns", worth=1000, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.ToadStone] = Item:new( {name="Toad Stone", worth=600, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.MagnificentMythicalBeastHide] = Item:new( {name="Magnificent Mythical Beast Hide", worth=2100, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.GrinningCatClaws] = Item:new( {name="Grinning Cat Claws", worth=400, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ThinFeathers] = Item:new( {name="Thin Feathers", worth=190, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ChargelessHorn] = Item:new( {name="Chargeless Horn", worth=220, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ChargedHorn] = Item:new( {name="Charged Horn", worth=730, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.LightningHorn] = Item:new( {name="Lightning Horn", worth=2230, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.S})
Treasure_DB[TREASURES.Weaponx1d] = Item:new( {name="Weapon  x 1d", worth=30, alchemy_color={  ALCHEMY_COLORS.Black}, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.RemainingMakoStones] = Item:new( {name="Remaining Mako Stones", worth=0, alchemy_color={  }, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.RemainingMakoStones] = Item:new( {name="Remaining Mako Stones", worth=0, alchemy_color={  }, alchemy_rank=RANK.B})
Treasure_DB[TREASURES.CrystallizedDaemonsBloodx1d] = Item:new( {name="Crystallized Daemon's Blood  x 1d", worth=800, alchemy_color={  ALCHEMY_COLORS.Red}, alchemy_rank=RANK.A})
Treasure_DB[TREASURES.ArcanaLanguageBook] = Item:new( {name="Arcana-Language Book", worth=170, alchemy_color={  ALCHEMY_COLORS.White}, alchemy_rank=RANK.A})

